### ISSUE TITLE
Update project to multi target frameworks

### ISSUE THREAD

**Issue by nlaveck** [vplauzon/AppInsights.TelemetryInitializers#1]
Hi,

I really like this implementation of the initializers!  However, I would like to use it for .NET Framework because I'm working with some legacy code bases.  I've forked your repo and I'm going to try to get it working for both .NET Framework 4.6.1 and .NET Standard 2.0.  If I get that working, would you accept a PR for it?

Thanks!

**Comment by vplauzon** [comment]
Hi!

Sure thing.  If the package could support both version of the Fx, the better!


Vincent-Philippe

**Comment by nlaveck** [comment]
Thanks!
